routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'web'], function () {
	Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:admin']], function () {
		Route::resource('jabatan', 'JabatanController');
		Route::resource('karyawan', 'KaryawanController');
	});
});

app/Jabatan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Jabatan extends Model
{
    //
    protected $fillable = ['Kode_jabatan', 'Nama_jabatan', 'Gaji_pokok'];
    protected $visible = ['Kode_jabatan', 'Nama_jabatan', 'Gaji_pokok'];
    public $timestamps = true;

    public function Karyawan()
    {
    	return $this->hasMany('App\Karyawan');
    }
}

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Jabatan;
use DB;
use Validator;
use Alert;

class JabatanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        //
        $jabatan = Jabatan::all();
        return view('jabatan.index', compact('jabatan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $untukid = DB::table('jabatans')->first('id');
        $newkode = $untukid + 1;
        $digit = strlen($newkode);
        if ($digit == '1') {
            $kode = "J00".$newkode;
        }
        elseif ($digit == '2') {
            $kode = "J0".$newkode;
        }
        elseif ($digit == '3') {
            $kode = "J".$newkode;
        }

        

        return view('jabatan.create', compact('kode'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $rules = [
            'Kode_jabatan' => 'required|max:255',
            'Nama_jabatan' => 'required',
            'Gaji_pokok' => 'required|numeric',
        ];

        $message = [
            'Kode_jabatan.required' => 'The Kode Jabatan is required',
            // 'Nama_jabatan.unique' => 'Nama Jabatan is already used find another Nama Jabatan',
            'Nama_jabatan.required' => 'The Nama Jabatan is required',
            'Gaji_pokok.numeric' => 'Besaran uang is number',
            'Gaji_pokok.required' => 'The Besaran Uang Jabatan is required',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails())
        {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }

        $jabatan = new Jabatan;
        $jabatan->Kode_jabatan = $request->Kode_jabatan;
        $jabatan->Nama_jabatan = $request->Nama_jabatan;
        $jabatan->Gaji_pokok = $request->Gaji_pokok;
        $jabatan->save();

        Alert::success('Data successfully saved','Good Job')->autoclose(1000);
        return redirect()->route('jabatan.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $jabatan = Jabatan::find($id);
        return view('jabatan.show', compact('jabatan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $jabatan = Jabatan::find($id);
        return view('jabatan.edit', compact('jabatan', 'kode'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $jabatan = Jabatan::find($id);

        $rules = [
            'Kode_jabatan' => 'required|max:255',
            'Nama_jabatan' => 'required',
            'Gaji_pokok' => 'required|numeric',
        ];

        $message = [
            'Kode_jabatan.required' => 'The Kode Jabatan is required',
            // 'Nama_jabatan.unique' => 'Nama Jabatan is already used find another Nama Jabatan',
            'Nama_jabatan.required' => 'The Nama Jabatan is required',
            'Gaji_pokok.numeric' => 'Besaran uang is number',
            'Gaji_pokok.required' => 'The Besaran Uang Jabatan is required',
        ];

        $validation = Validator::make($request->all(), $rules, $message);
        if ($validation->fails())
        {
            Alert::error('Sorry your data is invalid, Please try again!', 'Oops!')->persistent("Ok");
            return back()->withErrors($validation)->withInput();
        }

        $jabatan->Kode_jabatan = $request['Kode_jabatan'];
        $jabatan->Nama_jabatan = $request['Nama_jabatan'];
        $jabatan->Gaji_pokok = $request['Gaji_pokok'];
        $jabatan->save();

        Alert::success('Data successfully saved','Good Job')->autoclose(1000);
        return redirect()->route('jabatan.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Jabatan::find($id)->delete();
        return redirect()->route('jabatan.index')->with('Success!','Data Deleted Successfully');;
    }
}

resources/views/jabatan/create.blade.php
@extends('layouts.master')

@section('content')
<ul class="page-breadcrumb breadcrumb">
    <li>
        <a href="{{ url('home') }}">Home</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="{{ route('jabatan.index') }}">Jabatan</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span class="active">Tambah Data Jabatan</span>
    </li>
</ul>
<div class="portlet box blue-hoki">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-equalizer font-white-sunglo"></i>Form Jabatan </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
            <a href="javascript:;" class="reload" onclick="myFunction()"> </a>

        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        {!!Form::open(['url' => route('jabatan.store'), 'class' => 'form-horizontal']) !!}
            <div class="form-body">
                <div class="form-group{{ $errors->has('Kode_jabatan') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label">Kode Jabatan</label>
                    <div class="col-md-4">
                        <input type="text" class="form-control input-circle" value="{{ $kode }}" name="Kode_jabatan" readonly="">
                         @if ($errors->has('Kode_jabatan'))
                            <span class="help-block">
                                <strong>{{ $errors->first('Kode_jabatan') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="form-group{{ $errors->has('Nama_jabatan') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label">Jabatan</label>
                    <div class="col-md-4">
                        <input type="text" class="form-control input-circle" placeholder="Enter Nama Jabatan" name="Nama_jabatan">
                        @if ($errors->has('Nama_jabatan'))
                            <span class="help-block">
                                <strong>{{ $errors->first('Nama_jabatan') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="form-group{{ $errors->has('Gaji_pokok') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label">Besaran Uang</label>
                    <div class="col-md-4">
                        <input type="number" class="form-control input-circle" placeholder="Enter Besaran Uang" name="Gaji_pokok">
                        @if ($errors->has('Gaji_pokok'))
                            <span class="help-block">
                                <strong>{{ $errors->first('Gaji_pokok') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-circle green">Submit</button>
                        <button type="button" class="btn btn-circle grey-salsa btn-outline">Cancel</button>
                    </div>
                </div>
            </div>
        {!! Form::close() !!}
        <!-- END FORM-->
    </div>
</div>
@endsection

@section('scripts')
    <script>
        function myFunction() {
            location.reload();
        }
    </script>
@endsection

resources/views/jabatan/edit.blade.php
@extends('layouts.master')

@section('content')
<ul class="page-breadcrumb breadcrumb">
    <li>
        <a href="{{ url('home') }}">Home</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <a href="{{ route('jabatan.index') }}">Jabatan</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span class="active">Edit Data Jabatan</span>
    </li>
</ul>
<div class="portlet box purple">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-equalizer font-white-sunglo"></i>Form Jabatan </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
            <a href="javascript:;" class="reload" onclick="myFunction()"> </a>
        </div>
    </div>
    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        {!! Form::model($jabatan, ['method' => 'PATCH', 'route' => ['jabatan.update', $jabatan->id], 'class' => 'form-horizontal']) !!}
            <div class="form-body">
                <div class="form-group{{ $errors->has('Kode_jabatan') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label">Kode Jabatan</label>
                    <div class="col-md-4">
                        <input type="text" class="form-control input-circle" value="{{ $jabatan->Kode_jabatan }}" name="Kode_jabatan" readonly="">
                        @if ($errors->has('Kode_jabatan'))
                            <span class="help-block">
                                <strong>{{ $errors->first('Kode_jabatan') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="form-group{{ $errors->has('Nama_jabatan') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label">Jabatan</label>
                    <div class="col-md-4">
                        <input type="text" class="form-control input-circle" placeholder="Enter Nama Jabatan" name="Nama_jabatan" value="{{ $jabatan->Nama_jabatan }}">
                        @if ($errors->has('Nama_jabatan'))
                            <span class="help-block">
                                <strong>{{ $errors->first('Nama_jabatan') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="form-group{{ $errors->has('Gaji_pokok') ? ' has-error' : '' }}">
                    <label class="col-md-3 control-label">Besaran Uang</label>
                    <div class="col-md-4">
                        <input type="number" class="form-control input-circle" placeholder="Enter Besaran Uang" name="Gaji_pokok" value="{{ $jabatan->Gaji_pokok }}">
                        @if ($errors->has('Gaji_pokok'))
                            <span class="help-block">
                                <strong>{{ $errors->first('Gaji_pokok') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-offset-3 col-md-9">
                        <button type="submit" class="btn btn-circle green">Simpan</button>
                        <button type="button" class="btn btn-circle grey-salsa btn-outline">Cancel</button>
                    </div>
                </div>
            </div>
        {!! Form::close() !!}
        <!-- END FORM-->
    </div>
</div>
@endsection 	

@section('scripts')
    <script>
        function myFunction() {
            location.reload();
        }
    </script>
@endsection

resources/views/jabatan/index.blade.php
@extends('layouts.master')

@section('content')
<ul class="page-breadcrumb breadcrumb">
    <li>
        <a href="{{ url('home') }}">Home</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span class="active">Jabatan</span>
    </li>
</ul>
 <div class="portlet box green">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-diamond"></i>Data Jabatan </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"> </a>
            <a href="javascript:;" class="reload" onclick="myFunction()"> </a>
        </div>
    </div>
    <div class="portlet-body">
    	<a href="{{ route('jabatan.create') }}">
	    	<div class="btn-group btn-group-devided">
	            <label class="btn btn-outline btn-circle btn-sm blue"><span class="icon-plus"></span>&nbsp;&nbsp;Tambah Data</label>
	        </div>
        </a>
        <hr>
        <div class="table-scrollable">
            <table class="table table-striped table-bordered table-advance table-hover">
                <thead>
					<tr>
						<th><center>No</center></th>
						<th><center>Kode Jabatan</center></th>
						<th><center>Nama Jabatan</center></th>
						<th><center>Besaran Uang</center></th>
						<th colspan="2"><center>Action</center></th>
					</tr>
				</thead>
                <tbody>
					@if(count($jabatan) == 0)
						<tr>
							<td colspan="7"><center>Data Kosong!!</center></td>
						</tr>
					@else
						<?php
							$no = 1;
						?>
						@foreach($jabatan as $data)
							<tr>
								<td><center>{{ $no++ }}</center></td>
								<td>{{ $data->Kode_jabatan }}</td>
								<td>{{ $data->Nama_jabatan }}</td>
								<td><?php echo 'Rp. '.number_format($data->Gaji_pokok, 2, ",", "."); ?></td>
								<td><center><a href="{{ route('jabatan.edit', $data->id) }}" class="btn btn-outline btn-circle btn-sm purple"><i class="fa fa-edit"></i> Edit </a></center></td>
								<td><center>
									{!! Form::open(['class' => 'button', 'method' => 'DELETE', 'route' => ['jabatan.destroy', $data->id]]) !!}
										<button class="btn btn-outline btn-circle red btn-sm black remove">
                                            <i class="fa fa-trash-o"></i> Delete 
										</button>
									{!! Form::close() !!}
								</center></td>
							</tr>
						@endforeach
					@endif
				</tbody>
            </table>
        </div>
    </div>
</div>

@endsection

@section('scripts')
	<script>
		function myFunction() {
		    location.reload();
		}

		$(document).on('click', '.button', function (e) {
		    e.preventDefault();
		    var id = $(this).data('id');
		    swal({
		            title: "Are you sure?",
		            text: "You will not be able to recover this imaginary file!",
		            type: "warning",
		            showCancelButton: true,
				  	confirmButtonColor: "#DD6B55",
				  	confirmButtonText: "Yes, delete it!",
				  	cancelButtonText: "No, cancel please!",
				  	closeOnConfirm: false,
				  	closeOnCancel: false
		    },
	        function(isConfirm){
			  	if (isConfirm) {
			  		$.ajax({
		                type: "POST",
		                success:  swal("Deleted!", "Your imaginary file has been deleted.", "success"); 

		            });
				    // swal("Deleted!", "Your imaginary file has been deleted.", "success");
				} 
			 	else {
			    	swal("Cancelled", "Your imaginary file is safe :)", "error");
				}	
			});		        
		});
	</script>
@endsection